--- 
:site_name_legal: test
:newsletter: false
:meta_keywords: ""
:meta_robots: FOLLOW,INDEX
:meta_copyright: "Copyright \xC2\xA9 %Y Your Company's Legal Name"
:site_tag_line: ""
:meta_description: ""
:google_analytics_key: ""
:google_maps_key: ""
:site_name: FTest
:first_load: false
:meta_author: ""
